Planet Fitness CVE-2024-43201 and fix ROLIE feed
cisagov/CSAF pull request #119
Opened 2024-09-27 04:32 UTC by amanion-cisa

Adding Planet Fitness CVE-2024-43201 and fixing (or improving) broken ROLIE feed JSON

2024-09-27 12:04 UTC, justmurphy approved these changes
CSAF looks good.

@mstrad can you take a look at the files re: the ROLIE feed?

2024-09-27 14:14 UTC, amanion-cisa commented
The current IT/white ROLIE feed is [malformed](https://raw.githubusercontent.com/cisagov/CSAF/refs/heads/develop/csaf_files/IT/white/cisa-csaf-it-feed-tlp-white.json). I'm pretty sure this PR includes valid ROLIE, but I haven't found a validator that I trust.

@mstrad I started using [csaf-perl](https://github.com/giterlizzi/perl-CSAF) to generate the ROLIE feed file.

2024-09-30 15:44 UTC, mstrad commented
@amanion-cisa and @justmurphy I have review the PR and here is what I have found. 

- When including a "summary" in an entry: this ROLIE feed has it formatted incorrectly. Looking at the CSAF Schema's [examples](https://docs.oasis-open.org/csaf/csaf/v2.0/os/csaf-v2.0-os.html#7115-requirement-15-rolie-feed), along with other [examples](https://security.nozominetworks.com/csaf/feed-tlp-white.json) from the industry that use ROLIE feeds, those that use that field in an entry should format it as so
`"summary": {
            "content": "Vulnerabilities fixed in ABC 0.0.1"
},`

- The only other item I have for feedback is spacing. The colon should rest right next to the key of a field followed by a whitespace before the value is given. Example: **"key": **"value"
- Everything else appears to be correct.

2024-09-30 15:48 UTC, mstrad requested changes
Review finished. Please address previous comments.

2024-09-30 17:16 UTC, justmurphy commented
@mstrad I made the changes requested. Can you take another look?

2024-09-30 17:46 UTC, mstrad approved these changes

2024-09-30 17:51 UTC, merged